## Documentation: http://docs.travis-ci.com/user/languages/julia/
language: julia
os:
  - linux
  - osx
julia:
  - 0.7
  - 1.0
  - 1.1
  - 1.2
  - nightly
notifications:
  email: false
git:
  depth: 99999999

# comment the following lines to disallow failures on nightly julia
matrix:
  allow_failures:
  - julia: nightly

## uncomment and modify the following lines to manually install system packages
addons:
  apt:
    packages:
      - build-essential
      - gfortran
      - pkg-config
      - hdf5-tools

## uncomment the following lines to override the default test script
script:
  - if [[ -a .git/shallow ]]; then git fetch --unshallow; fi
  - julia ci_prep.jl
  - julia -e 'using Pkg; Pkg.build(); Pkg.test("RegisterQD"; coverage=true)'
after_success:
  # push coverage results to Codecov
  - julia -e 'import Pkg; Pkg.add("Coverage"); using Coverage; Codecov.submit(Codecov.process_folder())'
